// src/components/FormField.vue
<script setup>
import { controlTextColor } from '@/colorsPremium.js'
import { computed, useSlots } from 'vue'
import FormFieldHelp from '@/components/FormFieldHelp.vue'

const props = defineProps({
  label: {
    type: String,
    default: null
  },
  help: {
    type: String,
    default: null
  },
  horizontal: Boolean,
  addons: Boolean,
  grouped: Boolean,
  multiline: Boolean,
  error: {
    type: [Boolean, String],
    default: null
  },
  success: {
    type: [Boolean, String],
    default: null
  }
})

const slots = useSlots()

const upperWrapperClass = computed(() => {
  const base = [props.multiline ? '-mb-3' : 'mb-6']

  if (props.horizontal) {
    base.push('lg:gap-6 lg:grid-cols-5')
  }

  return base
})

const wrapperClass = computed(() => {
  const base = []
  const slotsLength = slots.default().length

  if (props.horizontal) {
    base.push('lg:col-span-4')

    if (!props.label) {
      base.push('lg:col-start-2')
    }
  }

  if (props.addons || props.grouped || props.multiline) {
    base.push('flex justify-start')
  } else {
    if (slotsLength > 1) {
      base.push('grid grid-cols-1 gap-3')
    }

    if (slotsLength === 2) {
      base.push('md:grid-cols-2')
    }

    if (slotsLength >= 3) {
      base.push('md:grid-cols-3')
    }
  }

  if (props.grouped) {
    base.push('space-x-3')
  }

  if (props.multiline) {
    base.push('flex-wrap')
  }

  return base
})

const labelClass = computed(() => {
  const base = []

  if (props.horizontal) {
    base.push('lg:mb-0')
  }

  const textColor = controlTextColor(props.error, props.success)

  if (textColor) {
    base.push(textColor)
  }

  return base
})
</script>

<template>
  <div class="grid grid-cols-1 last:mb-0" :class="upperWrapperClass">
    <label v-if="label" class="block font-bold mb-2" :class="labelClass">{{ label }}</label>
    <div :class="wrapperClass">
      <slot />
    </div>
    <FormFieldHelp
      class="mt-1"
      :class="{ 'lg:col-start-2 lg:col-span-4 lg:-mt-5': horizontal }"
      :help="help"
      :error="error"
      :success="success"
    />
  </div>
</template>

// src/componentsPrototies/FormField.tsx
import { Children, ReactNode } from 'react'
import { controlTextColor } from '../colorsPremium'
import FormFieldHelp from '../components/FormFieldHelp'

type Props = {
  label?: string
  help?: string
  error?: string
  success?: string
  horizontal: boolean
  addons: boolean
  grouped: boolean
  multiline: boolean
  children: ReactNode
}

const FormField = ({ children, ...props }: Props) => {
  const upperWrapperClass = [props.multiline ? '-mb-3' : 'mb-6']

  if (props.horizontal) {
    upperWrapperClass.push('lg:gap-6 lg:grid-cols-5')
  }

  const wrapperClass = []
  const slotsLength = Children.count(children)

  if (props.horizontal) {
    wrapperClass.push('lg:col-span-4')

    if (!props.label) {
      wrapperClass.push('lg:col-start-2')
    }
  }

  if (props.addons || props.grouped || props.multiline) {
    wrapperClass.push('flex justify-start')
  } else {
    if (slotsLength > 1) {
      wrapperClass.push('grid grid-cols-1 gap-3')
    }

    if (slotsLength === 2) {
      wrapperClass.push('md:grid-cols-2')
    }

    if (slotsLength >= 3) {
      wrapperClass.push('md:grid-cols-3')
    }
  }

  if (props.grouped) {
    wrapperClass.push('space-x-3')
  }

  if (props.multiline) {
    wrapperClass.push('flex-wrap')
  }

  const labelClass = []

  if (props.horizontal) {
    labelClass.push('lg:mb-0')
  }

  const textColor = controlTextColor(props.error, props.success)

  if (textColor) {
    labelClass.push(textColor)
  }

  return (
    <div className={`grid grid-cols-1 last:mb-0 ${upperWrapperClass.join(' ')}`}>
      {props.label && (
        <label v-if="label" className={`block font-bold mb-2 ${labelClass.join(' ')}`}>
          {props.label}
        </label>
      )}

      <div className={wrapperClass.join(' ')}>{children}</div>
      <FormFieldHelp
        className={`mt-1 ${props.horizontal ? 'lg:col-start-2 lg:col-span-4 lg:-mt-5' : ''}`}
        help={props.help}
        error={props.error}
        success={props.success}
      />
    </div>
  )
}

export default FormField
