// src/components/AsideMenuItem.tsx
import { mdiChevronRight, mdiMinus, mdiPlus } from '@mdi/js'
import Link from 'next/link'
import { useRouter } from 'next/router'
import { useEffect, useState } from 'react'
import { MenuAsideItemPremium } from '../interfaces/premium'
import { getButtonColor } from '../colors'
import { useAppSelector } from '../stores/hooks'
import BaseIcon from '../components/BaseIcon'
import AsideMenuList from './AsideMenuList'
import UpdateMark from '../components/UpdateMark'

type Props = {
  item: MenuAsideItemPremium
  activeSecondaryMenuKey?: string
  isDropdownList?: boolean
  isCompact?: boolean
  onMenuClick?: (item: MenuAsideItemPremium) => void
}

const AsideMenuItem = ({
  item,
  activeSecondaryMenuKey,
  isDropdownList,
  isCompact,
  onMenuClick,
}: Props) => {
  const stateAsideMenuItemStyle = useAppSelector((state) => state.style.asideMenuItemStyle)
  const stateAsideMenuItemInactiveStyle = useAppSelector(
    (state) => state.style.asideMenuItemInactiveStyle
  )
  const stateAsideMenuItemActiveBgStyle = useAppSelector(
    (state) => state.style.asideMenuItemActiveBgStyle
  )
  const stateAsideMenuItemActiveStyle = useAppSelector(
    (state) => state.style.asideMenuItemActiveStyle
  )
  const stateAsideMenuDropdownStyle = useAppSelector((state) => state.style.asideMenuDropdownStyle)

  const hasColor = !!item.color

  const asideMenuItemInactiveStyle = hasColor
    ? ''
    : `${stateAsideMenuItemInactiveStyle} dark:text-gray-300`

  const asideMenuItemActiveBgStyle = `${stateAsideMenuItemActiveBgStyle} dark:bg-slate-700/25`

  const asideMenuItemActiveStyle = hasColor ? '' : stateAsideMenuItemActiveStyle

  const [isDropdownActive, setIsDropdownActive] = useState(false)
  const [isLinkActive, setIsLinkActive] = useState(false)

  const asideMenuItemStyle = isLinkActive ? asideMenuItemActiveStyle : asideMenuItemInactiveStyle

  const { asPath, isReady } = useRouter()

  useEffect(() => {
    if (item.href && isReady) {
      const linkPathName = new URL(item.href, location.href).pathname

      const activePathname = new URL(asPath, location.href).pathname

      setIsLinkActive(linkPathName === activePathname)
    }
  }, [item.href, isReady, asPath])

  useEffect(() => {
    if (isCompact) {
      setIsDropdownActive(false)
    }
  }, [isCompact])

  const isSecondaryMenuActive =
    activeSecondaryMenuKey && item.key && item.key === activeSecondaryMenuKey

  const componentClass = [
    'flex cursor-pointer',
    isDropdownList ? 'py-3 px-6 text-sm' : 'py-3',
    hasColor
      ? getButtonColor(item.color, false, true)
      : `${stateAsideMenuItemStyle} dark:hover:bg-gray-700/50`,
  ]

  if (
    (!hasColor && (isDropdownActive || isSecondaryMenuActive)) ||
    (isLinkActive && !activeSecondaryMenuKey)
  ) {
    componentClass.push(asideMenuItemActiveBgStyle)
  }

  const componentClassName = componentClass.join(' ')

  const hasDropdown = !!item.menu

  const hasSecondary = !!item.menuSecondary

  const hasSub = hasDropdown || hasSecondary

  let subIcon = isDropdownActive ? mdiMinus : mdiPlus

  if (hasSecondary) {
    subIcon = mdiChevronRight
  }

  const handleNonLinkClick = () => {
    if (hasDropdown) {
      setIsDropdownActive(!isDropdownActive)
    }

    if (onMenuClick) {
      onMenuClick(item)
    }
  }

  const updateMarkPositionBase = 'top-0.5 right-4'

  const updateMarkPosition = isCompact
    ? `${updateMarkPositionBase} lg:right-6`
    : updateMarkPositionBase

  const innerContents = (
    <>
      {!!item.icon && (
        <BaseIcon
          path={item.icon}
          className={`flex-none transition-size ${asideMenuItemStyle} ${
            item.updateMark ? 'relative' : ''
          }`}
          w={isCompact ? 'w-16 lg:w-20' : 'w-16'}
          size={18}
        >
          {!!item.updateMark && (
            <UpdateMark color={item.updateMark} position={updateMarkPosition} />
          )}
        </BaseIcon>
      )}
      <span
        className={`grow animate-fade-in text-ellipsis line-clamp-1 ${asideMenuItemStyle} ${
          isCompact ? 'lg:hidden' : ''
        } ${hasSub ? '' : 'pr-12'}`}
      >
        {item.label}
      </span>
      {hasSub && (
        <BaseIcon
          path={subIcon}
          className={`flex-none animate-fade-in-fast ${asideMenuItemStyle} ${
            isCompact ? 'lg:hidden' : ''
          }`}
          w="w-12"
        />
      )}
    </>
  )

  return (
    <li>
      {!item.href && (
        <div className={componentClassName} onClick={handleNonLinkClick}>
          {innerContents}
        </div>
      )}
      {item.href && (
        <Link href={item.href} target={item.target} className={`${componentClassName}`}>
          {innerContents}
        </Link>
      )}
      {hasDropdown && (
        <AsideMenuList
          menu={item.menu}
          className={`${stateAsideMenuDropdownStyle} ${
            isDropdownActive ? 'block dark:bg-slate-800/50' : 'hidden'
          }`}
          isDropdownList
        />
      )}
    </li>
  )
}

export default AsideMenuItem

// src/components/AsideMenuItem.vue
<script setup>
import { ref, computed, watch } from 'vue'
import { RouterLink } from 'vue-router'
import { mdiMinus, mdiPlus, mdiChevronRight } from '@mdi/js'
import { getButtonColor } from '@/colors.js'
import BaseIcon from '@/components/BaseIcon.vue'
import AsideMenuList from '@/components/AsideMenuList.vue'
import UpdateMark from '@/components/UpdateMark.vue'

const props = defineProps({
  item: {
    type: Object,
    required: true
  },
  activeSecondaryMenuKey: {
    type: String,
    default: null
  },
  isDropdownList: Boolean,
  isCompact: Boolean
})

const emit = defineEmits(['menu-click'])

const asideMenuItemInactiveStyle = computed(() =>
  hasColor.value ? '' : `aside-menu-item-inactive dark:text-gray-300`
)

const asideMenuItemActiveBgStyle = `aside-menu-item-active-bg dark:bg-slate-700/25`

const asideMenuItemActiveStyle = computed(() => (hasColor.value ? '' : 'aside-menu-item-active'))

const isAsideCompact = computed(() => props.isCompact)

watch(isAsideCompact, (value) => {
  if (value) {
    isDropdownActive.value = false
  }
})

const isDropdownActive = ref(false)

const isSecondaryMenuActive = computed(
  () =>
    props.activeSecondaryMenuKey &&
    props.item?.key &&
    props.item?.key === props.activeSecondaryMenuKey
)

const hasColor = computed(() => props.item && props.item.color)

const componentClass = computed(() => {
  const base = [
    props.isDropdownList ? 'py-3 px-6 text-sm' : 'py-3',
    hasColor.value
      ? getButtonColor(props.item.color, false, true)
      : `aside-menu-item dark:hover:bg-gray-700/50`
  ]

  if (!hasColor.value && (isDropdownActive.value || isSecondaryMenuActive.value)) {
    base.push(asideMenuItemActiveBgStyle.value)
  }

  return base
})

const hasDropdown = computed(() => !!props.item.menu)

const hasSecondary = computed(() => !!props.item.menuSecondary)

const hasSub = computed(() => hasDropdown.value || hasSecondary.value)

const subIcon = computed(() => {
  if (hasSecondary.value) {
    return mdiChevronRight
  }

  return isDropdownActive.value ? mdiMinus : mdiPlus
})

const menuClick = (event) => {
  emit('menu-click', event, props.item)

  if (hasDropdown.value) {
    isDropdownActive.value = !isDropdownActive.value
  }
}

const updateMarkPosition = computed(() => {
  const base = 'top-0.5 right-4'

  return props.isCompact ? `${base} lg:right-6` : base
})
</script>

<template>
  <li>
    <component
      :is="item.to ? RouterLink : 'a'"
      v-slot="vSlot"
      :to="item.to ?? null"
      :href="item.href ?? null"
      :target="item.target ?? null"
      :exact-active-class="activeSecondaryMenuKey ? null : asideMenuItemActiveBgStyle"
      class="flex cursor-pointer"
      :class="componentClass"
      @click="menuClick"
    >
      <BaseIcon
        v-if="item.icon"
        :path="item.icon"
        class="flex-none transition-size"
        :class="[
          vSlot && vSlot.isExactActive ? asideMenuItemActiveStyle : asideMenuItemInactiveStyle,
          { relative: item.updateMark }
        ]"
        :w="isCompact ? 'w-16 lg:w-20' : 'w-16'"
        :size="18"
      >
        <UpdateMark
          v-if="item.updateMark"
          :color="item.updateMark"
          :position="updateMarkPosition"
        />
      </BaseIcon>
      <span
        class="grow animate-fade-in text-ellipsis line-clamp-1"
        :class="[
          { 'lg:hidden': isCompact, 'pr-12': !hasSub },
          vSlot && vSlot.isExactActive ? asideMenuItemActiveStyle : asideMenuItemInactiveStyle
        ]"
        >{{ item.label }}</span
      >
      <BaseIcon
        v-if="hasSub"
        :path="subIcon"
        class="flex-none animate-fade-in-fast"
        :class="[
          { 'lg:hidden': isCompact },
          vSlot && vSlot.isExactActive ? asideMenuItemActiveStyle : asideMenuItemInactiveStyle
        ]"
        w="w-12"
      />
    </component>
    <AsideMenuList
      v-if="hasDropdown"
      :menu="item.menu"
      :class="isDropdownActive ? 'block dark:bg-slate-800/50' : 'hidden'"
      class="aside-menu-dropdown"
      is-dropdown-list
    />
  </li>
</template>
