// src/components/FooterBar.tsx
import React, { ReactNode } from 'react'
import { containerMaxW } from '../config'
import SofyntelligenLogo from './SofyntelligenLogo'

type Props = {
  children: ReactNode
}

export default function FooterBar({ children }: Props) {
  const year = new Date().getFullYear()

  return (
    <footer className={`py-2 px-6 ${containerMaxW}`}>
      <div className="block md:flex items-center justify-between">
        <div className="text-center md:text-left mb-6 md:mb-0">
          <b>
            &copy;{year},{` `}
            <a href="http://localhost:3001/error" rel="noreferrer" target="_blank">
              Sofyntelligen.com
            </a>
            .
          </b>
          {` `}
          {children}
        </div>
        <div className="md:py-2">
          <a href="http://localhost:3001/error" rel="noreferrer" target="_blank">
            <SofyntelligenLogo className="w-auto h-8 md:h-6 mx-auto" />
          </a>
        </div>
      </div>
    </footer>
  )
}

// src/components/FooterBar.vue
<script setup>
import { containerMaxW } from '@/config.js'
import BaseLevel from '@/components/BaseLevel.vue'
import JustboilLogo from '@/components/JustboilLogo.vue'

</script>

<template>
  <footer class="py-2 px-6" :class="containerMaxW">
    <BaseLevel>
      <div class="text-center md:text-left">
        <b>&copy; 2023, <a href="https://github.com/josedanielhernandezosorio" target="_blank">Sofyntelligen.com</a>.</b>
        <slot />
      </div>
      <div class="md:py-2">
        <a href="">
          <JustboilLogo class="w-auto h-8 md:h-6" />
        </a>
      </div>
    </BaseLevel>
  </footer>
</template>
