// src/components/SnackBarItem.tsx
import { useState } from 'react'
import { SnackBarMessage } from '../layouts/interfaces'
import { getButtonColor } from '../layouts/config/colors'
import { useAppDispatch } from '../stores/hooks'
import { cancelMessage } from '../stores/snackBarSlice'

const SnackBarItem = ({ lifetime, timestamp, text, color }: SnackBarMessage) => {
  const [isActive, setIsActive] = useState(true)

  const dispatch = useAppDispatch()

  if (lifetime) {
    setTimeout(() => {
      setIsActive(false)
      dispatch(cancelMessage(timestamp))
    }, lifetime)
  }

  const cancelClick = () => {
    setIsActive(false)

    if (!lifetime) {
      dispatch(cancelMessage(timestamp))
    }
  }

  if (!isActive) {
    return null
  }

  return (
    <div
      v-show="isActive"
      className={`${getButtonColor(
        color,
        false,
        true
      )} self-end my-1.5 md:my-3 first:mb-0 px-6 py-4 shadow overflow-hidden w-full md:rounded-xl md:w-auto md:max-w-full cursor-pointer pointer-events-auto animate-fade-in-up-fast`}
      onClick={cancelClick}
    >
      {text}
    </div>
  )
}

export default SnackBarItem

// src/components/SnackBarItem.vue
<script setup>
import { ref } from 'vue'
import { getButtonColor } from '@/colors.js'

const props = defineProps({
  lifetime: {
    type: Number,
    required: true,
    validator: (value) => value >= 0
  },
  timestamp: {
    type: Number,
    required: true
  },
  text: {
    type: String,
    required: true
  },
  color: {
    type: String,
    required: true,
    validator: (value) => ['contrast', 'info', 'success', 'warning', 'danger'].indexOf(value) > -1
  }
})

const emit = defineEmits(['cancel'])

const isActive = ref(false)

setTimeout(() => {
  isActive.value = true
})

if (props.lifetime) {
  setTimeout(() => {
    isActive.value = false

    cancelEmit()
  }, props.lifetime)
}

const cancelEmit = () => {
  setTimeout(() => {
    emit('cancel', props.timestamp)
  }, 250)
}

const cancelClick = () => {
  isActive.value = false

  if (!props.lifetime) {
    cancelEmit()
  }
}
</script>

<template>
  <transition
    enter-active-class="animate-fade-in-up-fast"
    leave-active-class="animate-fade-out-down-fast"
  >
    <div
      v-show="isActive"
      :class="getButtonColor(color, false, true)"
      class="self-end my-3 px-6 py-4 shadow overflow-hidden w-full md:rounded-xl md:w-auto md:max-w-full cursor-pointer pointer-events-auto"
      @click="cancelClick"
    >
      {{ text }}
    </div>
  </transition>
</template>
