// src/components/UserCardProfileNumber.tsx
import NumberDynamic from '../components/NumberDynamic'

type Props = {
    number: number
    label: string
    className?: string
}

const UserCardProfileNumber = ({number, label, className}: Props) => {
    return (
        <div className={`text-center ${className}`}>
            <h2 className="text-xl font-medium">
                <NumberDynamic value={number}/>
            </h2>
            <p className="text-xs uppercase">{label}</p>
        </div>
    )
}

export default UserCardProfileNumber

// src/components/UserCardProfileNumber.vue
<script setup>
import NumberDynamic from '@/components/NumberDynamic.vue'

defineProps({
  number: {
    type: Number,
    required: true
  },
  label: {
    type: String,
    required: true
  }
})
</script>

<template>
  <div class="text-center">
    <h2 class="text-xl font-medium">
      <NumberDynamic :value="number" />
    </h2>
    <p class="text-xs uppercase">{{ label }}</p>
  </div>
</template>
