// src/components/UserCard.tsx
import {mdiCheckDecagram} from '@mdi/js'
import {Field, Form, Formik} from 'formik'
import {useAppSelector} from '../stores/hooks'
import CardBox from './CardBox'
import FormCheckRadio from './FormCheckRadio'
import PillTag from './PillTag'
import UserAvatarCurrentUser from './UserAvatarCurrentUser'

type Props = {
    className?: string
}

const UserCard = ({className}: Props) => {
    const userName = useAppSelector((state) => state.main.userName)

    return (
        <CardBox className={className}>
            <div className="flex flex-col lg:flex-row items-center justify-around lg:justify-center">
                <UserAvatarCurrentUser className="mb-6 lg:mb-0 lg:mx-12"/>
                <div className="space-y-3 text-center md:text-left lg:mx-12">
                    <div className="flex justify-center md:block">
                        <Formik
                            initialValues={{
                                notifications: ['1'],
                            }}
                            onSubmit={(values) => alert(JSON.stringify(values, null, 2))}
                        >
                            <Form>
                                <FormCheckRadio type="switch" label="Notifications">
                                    <Field type="checkbox" name="notifications" value={'1'}/>
                                </FormCheckRadio>
                            </Form>
                        </Formik>
                    </div>
                    <h1 className="text-2xl">
                        Howdy, <b>{userName}</b>!
                    </h1>
                    <p>
                        Last login <b>12 mins ago</b> from <b>127.0.0.1</b>
                    </p>
                    <div className="flex justify-center md:block">
                        <PillTag label="Verified" color="info" icon={mdiCheckDecagram}/>
                    </div>
                </div>
            </div>
        </CardBox>
    )
}

export default UserCard

// src/components/UserCard.vue
<script setup>
import { computed, ref } from 'vue'
import { useMainStore } from '@/stores/main'
import { mdiCheckDecagram } from '@mdi/js'
import BaseLevel from '@/components/BaseLevel.vue'
import UserAvatarCurrentUser from '@/components/UserAvatarCurrentUser.vue'
import CardBox from '@/components/CardBox.vue'
import FormCheckRadio from '@/components/FormCheckRadio.vue'
import PillTag from '@/components/PillTag.vue'

const mainStore = useMainStore()

const userName = computed(() => mainStore.userName)

const userSwitchVal = ref(false)
</script>

<template>
  <CardBox flex="flex-row" class="items-center">
    <BaseLevel type="justify-around lg:justify-center">
      <UserAvatarCurrentUser class="lg:mx-12" />
      <div class="space-y-3 text-center md:text-left lg:mx-12">
        <div class="flex justify-center md:block">
          <FormCheckRadio
            v-model="userSwitchVal"
            name="notifications-switch"
            type="switch"
            label="Notifications"
            :input-value="true"
          />
        </div>
        <h1 class="text-2xl">
          Howdy, <b>{{ userName }}</b
          >!
        </h1>
        <p>Last login <b>12 mins ago</b> from <b>127.0.0.1</b></p>
        <div class="flex justify-center md:block">
          <PillTag label="Verified" color="info" :icon="mdiCheckDecagram" />
        </div>
      </div>
    </BaseLevel>
  </CardBox>
</template>
