// src/components/UserAvatarCurrentUserWithUpload.vue
<script setup>
import UserAvatarCurrentUser from '@/components/UserAvatarCurrentUser.vue'
import { mdiCamera } from '@mdi/js'
import FormFilePicker from '@/components/FormFilePicker.vue'
</script>

<template>
  <UserAvatarCurrentUser class="relative">
    <div class="absolute right-0 bottom-0">
      <FormFilePicker :icon="mdiCamera" is-round-icon />
    </div>
  </UserAvatarCurrentUser>
</template>

// src/components/UserAvatarCurrentUserWithUpload.tsx
import {mdiCamera} from '@mdi/js'
import FormFilePicker from '../components/FormFilePicker'
import UserAvatarCurrentUser from '../components/UserAvatarCurrentUser'

type Props = {
    className?: string
}

const UserAvatarCurrentUserWithUpload = ({className}: Props) => {
    return (
        <UserAvatarCurrentUser className={`relative ${className}`}>
            <div className="absolute right-0 bottom-0">
                <FormFilePicker icon={mdiCamera} color="info" isRoundIcon/>
            </div>
        </UserAvatarCurrentUser>
    )
}

export default UserAvatarCurrentUserWithUpload
